const phrases = [
    "I am firing my laser",
    "Hey look, a quarter!",
    "It's over 9000!",
    "I see what you did there",
    "Challenge accepted",
    "This is Sparta!",
    "Y U NO",
    "All your base are belong to us",
    "I can haz cheeseburger?",
    "Badger, badger, badger",
    "Keyboard cat",
    "Nyan Cat",
    "Charlie bit my finger",
    "Double Rainbow",
    "Chocolate Rain",
    "Doge",
    "Shut up and take my money",
    "I'm not a robot",
    "Just do it",
    "Keep calm and carry on",
    "Ain't nobody got time for that",
    "YOLO",
    "You shall not pass!",
    "Winter is coming",
    "Wubba lubba dub dub",
    "Rickroll",
    "Leeroy Jenkins",
    "I can't believe it's not butter",
    "Not all heroes wear capes",
    "That's what she said",
    "I'm in me mum's car",
    "How do you do, fellow kids?",
    "It's a trap!",
    "A potato flew around my room",
    "To be or not to be",
    "I am the one who knocks",
    "I have a cunning plan",
    "Resistance is futile",
    "Elementary, my dear Watson",
    "I'll be back",
    "May the force be with you",
    "Live long and prosper",
    "Make it so", "Engage!",
    "I'll be there for you",
    "Winter is coming",
    "Winter has come",
    "Expecto Patronum",
    "Avada Kedavra"
]

module.exports = phrases